# Generated by Django 5.2.5 on 2025-12-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marca as categorias oficiais (A, B, C, D) criadas pelo sistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Mista (atua em duplas mistas)')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='tournaments.category')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Se vazio, será montado automaticamente com os nomes dos atletas.', max_length=120)),
                ('division', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Mista')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='tournaments.category')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_teams', to='tournaments.participant')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_teams', to='tournaments.participant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('division', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Mista')], default='X', max_length=1)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_sets', models.PositiveSmallIntegerField(default=3, help_text='Quantidade máxima de sets por partida (melhor de 3 por padrão).')),
                ('tie_break_enabled', models.BooleanField(default=True, help_text='Se verdadeiro, partidas podem encerrar em tie-break.')),
                ('tie_break_points', models.PositiveSmallIntegerField(choices=[(7, '7 pontos'), (10, '10 pontos')], default=7, help_text='Escolha se o tie-break será jogado em 7 ou 10 pontos + 2 de diferença.')),
                ('tie_break_margin', models.PositiveSmallIntegerField(default=2, help_text='Diferença mínima para fechar o tie-break (regra +2).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.category')),
            ],
            options={
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(default='Fase de grupos', help_text='Ex.: Fase de grupos, Quartas, Semi, Final.', max_length=80)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('tie_break_played', models.BooleanField(default=False)),
                ('team_one_sets_won', models.PositiveSmallIntegerField(default=0)),
                ('team_two_sets_won', models.PositiveSmallIntegerField(default=0)),
                ('team_one_point_sequence', models.JSONField(blank=True, default=list)),
                ('team_two_point_sequence', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_one', to='tournaments.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_two', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ('tournament', 'round_name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('team_one_games', models.PositiveSmallIntegerField()),
                ('team_two_games', models.PositiveSmallIntegerField()),
                ('tie_break_played', models.BooleanField(default=False)),
                ('team_one_tie_break_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_two_tie_break_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='tournaments.match')),
            ],
            options={
                'ordering': ('set_number',),
                'constraints': [models.UniqueConstraint(fields=('match', 'set_number'), name='unique_set_number_per_match')],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('player_one', 'player_two', 'category', 'division'), name='unique_team_pair'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('player_one', models.F('player_two')), _negated=True), name='team_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_one', models.F('team_two')), _negated=True), name='match_distinct_teams'),
        ),
    ]
