# Generated by Django 5.2.5 on 2025-12-02 00:51

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('tournaments', 'Category')
    defaults = [
        ("A", "Atletas profissionais e avançados"),
        ("B", "Avançado/intermediário"),
        ("C", "Intermediário"),
        ("D", "Iniciante"),
    ]
    for name, description in defaults:
        Category.objects.get_or_create(
            name=name,
            defaults={"description": description, "is_default": True},
        )


def unseed_categories(apps, schema_editor):
    Category = apps.get_model('tournaments', 'Category')
    Category.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
