# Generated by Django 5.2.5 on 2025-12-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pairing_mode', models.CharField(choices=[('undecided', 'Definir depois'), ('manual', 'Manual'), ('random', 'Sorteio')], default='undecided', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='setscore',
            name='set_number',
            field=models.PositiveSmallIntegerField(verbose_name='Número do set'),
        ),
        migrations.AlterField(
            model_name='setscore',
            name='team_one_games',
            field=models.PositiveSmallIntegerField(verbose_name='Games da dupla A'),
        ),
        migrations.AlterField(
            model_name='setscore',
            name='team_one_tie_break_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pontos tie-break dupla A'),
        ),
        migrations.AlterField(
            model_name='setscore',
            name='team_two_games',
            field=models.PositiveSmallIntegerField(verbose_name='Games da dupla B'),
        ),
        migrations.AlterField(
            model_name='setscore',
            name='team_two_tie_break_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pontos tie-break dupla B'),
        ),
        migrations.AlterField(
            model_name='setscore',
            name='tie_break_played',
            field=models.BooleanField(default=False, verbose_name='Tie-break disputado?'),
        ),
        migrations.CreateModel(
            name='DailyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.dailyguide')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DailyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_teams', to='tournaments.dailyguide')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_daily_teams', to='tournaments.dailyparticipant')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_daily_teams', to='tournaments.dailyparticipant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DailyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_score', models.PositiveSmallIntegerField(default=0, verbose_name='Games Dupla A')),
                ('team_two_score', models.PositiveSmallIntegerField(default=0, verbose_name='Games Dupla B')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.dailyguide')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_one', to='tournaments.dailyteam')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_two', to='tournaments.dailyteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_matches_won', to='tournaments.dailyteam')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='dailyteam',
            constraint=models.CheckConstraint(condition=models.Q(('player_one', models.F('player_two')), _negated=True), name='daily_team_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='dailymatch',
            constraint=models.CheckConstraint(condition=models.Q(('team_one', models.F('team_two')), _negated=True), name='daily_match_distinct_teams'),
        ),
    ]
