# Generated by Django 5.2.5 on 2025-12-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_dailyguide_alter_setscore_set_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_entries",
                        to="tournaments.participant",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ("participant__full_name",),
                "unique_together": {("tournament", "participant")},
            },
        ),
        migrations.CreateModel(
            name="TournamentTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_label", models.CharField(blank=True, max_length=5)),
                (
                    "stage",
                    models.CharField(
                        choices=[("group", "Fase de grupos"), ("knockout", "Mata-mata")],
                        default="group",
                        max_length=15,
                    ),
                ),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_presences",
                        to="tournaments.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_teams",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ("group_label", "team__name"),
                "unique_together": {("tournament", "team")},
            },
        ),
    ]
